Add 'extern' statements to public headers for C++ compatibility
quickjs-ng/quickjs pull request #450
Opened 2024-07-01 10:33 UTC by andrjohns

Currently only the `quickjs.h` and `quicks-libc.h` have `extern "C"` statements for compiling under C++, this PR adds them to the other public headers

2024-07-01 10:44 UTC, saghul approved these changes

2024-07-01 13:41 UTC, chqrlie requested changes

2024-07-01 13:41 UTC, chqrlie commented on cutils.h
>  #endif
I think the `#include <windows.h>` should be outside the `extern "C"` block.

2024-07-14 22:23 UTC, chqrlie approved these changes

2024-07-14 22:23 UTC, merged